CREATE TABLE channels (
	id INTEGER PRIMARY KEY,
	tab_id INTEGER DEFAULT 0,
	title TEXT DEFAULT NULL,
	link TEXT DEFAULT NULL,
	image TEXT DEFAULT NULL,
	FOREIGN KEY (tab_id) REFERENCES tabs(id) ON DELETE CASCADE ON UPDATE NO ACTION
);