CREATE TABLE enclosures (
   id INTEGER PRIMARY KEY,
   item_id INTEGER DEFAULT 0,
   url TEXT UNIQUE NOT NULL,
   path TEXT DEFAULT NULL,
   length INT DEFAULT 0,
   type TEXT DEFAULT NULL,
   FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE ON UPDATE NO ACTION
);